{% set name = "muspinsim" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/muspinsim-{{ version }}.tar.gz
  sha256: 7ad4b6048c588bec54120d7e57029862e5d4406d62466367a5b9cc27704ed005

build:
  number: 0
  skip: true  # [py<38]
  script_env:
    - MUSPINSIM_WITH_OPENMP=1
  entry_points:
    - muspinsim = muspinsim.__main__:main
    - muspinsim.mpi = muspinsim.__main__:main_mpi
    - muspinsim-gen = muspinsim.tools.generator:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - numpy
    - scipy
    - cython
    - pybind11
    - qutip
  run:
    - lark
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - soprano
    - qutip
    - pybind11
    - cython
    - ase

test:
  imports:
    - muspinsim
  commands:
    - pip check
    - muspinsim --help
    - muspinsim.mpi --help
    - muspinsim-gen --help
    - pytest --pyargs muspinsim
  requires:
    - pip
    - pytest

about:
  home: https://github.com/muon-spectroscopy-computational-project/muspinsim
  summary: Full quantum simulation of muon experiments
  license: MIT
  license_file: LICENSE
  doc_url: https://muon-spectroscopy-computational-project.github.io/muspinsim/
  dev_url: https://github.com/muon-spectroscopy-computational-project/muspinsim

extra:
  recipe-maintainers:
    - joelvdavies
    - patrick-austin
    - leandro-liborio
