{% set name = "muspinsim" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/muspinsim-{{ version }}.tar.gz
  sha256: 88aa891d01325fe347e3859ffd59fa0ee31fd9ae3750ae3a701aff5483e973c7

build:
  number: 0
  skip: True  # [py<38]
  script_env:
    - MUSPINSIM_WITH_OPENMP=1
  entry_points:
    - muspinsim = muspinsim.__main__:main
    - muspinsim.mpi = muspinsim.__main__:main_mpi
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - numpy
    - scipy
    - cython
    - pybind11
    - qutip
  run:
    - lark
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - soprano
    - qutip
    - pybind11
    - cython
    - ase

test:
  imports:
    - muspinsim
  commands:
    - pip check
    - muspinsim --help
    - muspinsim.mpi --help
    - pytest --pyargs muspinsim
  requires:
    - pip
    - pytest

about:
  home: https://github.com/muon-spectroscopy-computational-project/muspinsim
  summary: Full quantum simulation of muon experiments
  license: MIT
  license_file: LICENSE
  doc_url: https://muon-spectroscopy-computational-project.github.io/muspinsim/
  dev_url: https://github.com/muon-spectroscopy-computational-project/muspinsim

extra:
  recipe-maintainers:
    - joelvdavies
    - patrick-austin
    - leandro-liborio
    - elichad
