{% set name = "muspinsim" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/muspinsim-{{ version }}.tar.gz
  sha256: 88aa891d01325fe347e3859ffd59fa0ee31fd9ae3750ae3a701aff5483e973c7

build:
  entry_points:
    - muspinsim = muspinsim.__main__:main
    - muspinsim.mpi = muspinsim.__main__:main_mpi
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lark
    - numpy
    - python >=3.6
    - scipy
    - soprano

test:
  imports:
    - muspinsim
  commands:
    - pip check
    - muspinsim --help
    - muspinsim.mpi --help
  requires:
    - pip

about:
  home: https://github.com/muon-spectroscopy-computational-project/muspinsim
  summary: Full quantum simulation of muon experiments
  license: MIT
  license_file: LICENSE
  doc_url: https://muon-spectroscopy-computational-project.github.io/muspinsim/
  dev_url: https://github.com/muon-spectroscopy-computational-project/muspinsim

extra:
  recipe-maintainers:
    - joelvdavies
    - patrick-austin
    - leandro-liborio
    - elichad
