{% set name = "muspinsim" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/muspinsim-{{ version }}.tar.gz
  sha256: 5ca8ceb3ac9b1633e9c274e117fc4854b6da5443ff2362a609f0a2fab676250c

build:
  entry_points:
    - muspinsim = muspinsim.__main__:main
    - muspinsim.mpi = muspinsim.__main__:main_mpi
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lark
    - numpy
    - python >=3.6
    - scipy
    - soprano

test:
  imports:
    - muspinsim
  commands:
    - pip check
    - muspinsim --help
    - muspinsim.mpi --help
  requires:
    - pip

about:
  home: https://github.com/muon-spectroscopy-computational-project/muspinsim
  summary: Full quantum simulation of muon experiments
  license: MIT
  license_file: LICENSE
  doc_url: https://muon-spectroscopy-computational-project.github.io/muspinsim/
  dev_url: https://github.com/muon-spectroscopy-computational-project/muspinsim

extra:
  recipe-maintainers:
    - patrick-austin
    - leandro-liborio
    - elichad
